// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPkNIi2eJCvD81HsXu0Y2qlXwH6vLKhMo',
    appId: '1:262906259636:web:1c05db9045126f749a0fe1',
    messagingSenderId: '262906259636',
    projectId: 'eddiesthesis',
    authDomain: 'eddiesthesis.firebaseapp.com',
    storageBucket: 'eddiesthesis.appspot.com',
    measurementId: 'G-8E6962KSCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAVEFCLsIUReWYa79gVOQZ7C4ppgj7NJ4',
    appId: '1:262906259636:android:6bcd8cf0931611c29a0fe1',
    messagingSenderId: '262906259636',
    projectId: 'eddiesthesis',
    storageBucket: 'eddiesthesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzx954WHQ2nwMgAfcIxhCoAmOSB2uA5fU',
    appId: '1:262906259636:ios:ed4294c7a4900c1d9a0fe1',
    messagingSenderId: '262906259636',
    projectId: 'eddiesthesis',
    storageBucket: 'eddiesthesis.appspot.com',
    iosBundleId: 'com.example.eddiesThesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzx954WHQ2nwMgAfcIxhCoAmOSB2uA5fU',
    appId: '1:262906259636:ios:ed4294c7a4900c1d9a0fe1',
    messagingSenderId: '262906259636',
    projectId: 'eddiesthesis',
    storageBucket: 'eddiesthesis.appspot.com',
    iosBundleId: 'com.example.eddiesThesis',
  );
}
